[libraries]
commons-csv = { module = "org.apache.commons:commons-csv", version = "1.14.1" }
commons-io = { module = "commons-io:commons-io", version = "2.21.0" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version = "6.0.2" }
lwjgl = { module = "org.lwjgl:lwjgl", version = "3.3.6" }
lwjgl-glfw = { module = "org.lwjgl:lwjgl-glfw" }
lwjgl-opengl = { module = "org.lwjgl:lwjgl-opengl" }
lwjgl-stb = { module = "org.lwjgl:lwjgl-stb" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
slf4j-jul = {  module = "org.slf4j:slf4j-jdk14" }
slf4j-simple = { module = "org.slf4j:slf4j-simple" }
