[versions]
assertj = "3.27.3"
guava = "33.4.8-jre"
guice = "5.1.0"
httpcomponents = "4.5.14"
jackson = "2.13.5"
jakarta-activation = "1.2.2"
jakarta-inject = "1.0.5"
jakarta-mail = "1.6.7"
jakarta-servlet = "4.0.4"
jsr305 = "3.0.2"
junit5 = "5.8.2"
opensaml = "2.6.4"
org-json = "20250107"
org-reflections = "0.9.11"
poi = "5.4.0"
resteasy = "4.7.10.Final"
slf4j = "1.7.36"
solrj = "7.7.3"
typesafeconfig = "0.1.0"
velocity = "2.4.1"
zookeeper = "3.9.3"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
commons-io = { module = "commons-io:commons-io" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
guice-servlet = { module = "com.google.inject.extensions:guice-servlet" }
httpcomponents-fluent-hc = { module = "org.apache.httpcomponents:fluent-hc", version.ref = "httpcomponents" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-datatype-json-org = { module = "com.fasterxml.jackson.datatype:jackson-datatype-json-org" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
jakarta-activation = { module = "com.sun.activation:jakarta.activation", version.ref = "jakarta-activation" }
jakarta-inject-api = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakarta-inject" }
jakarta-mail-impl = { module = "com.sun.mail:jakarta.mail", version.ref = "jakarta-mail" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "jakarta-servlet" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
opensaml = { module = "org.opensaml:opensaml", version.ref = "opensaml" }
org-json = { module = "org.json:json", version.ref = "org-json" }
org-reflections = { module = "org.reflections:reflections", version.ref = "org-reflections" }
poi = { module = "org.apache.poi:poi", version.ref = "poi" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml" }
resteasy-core = { module = "org.jboss.resteasy:resteasy-core", version.ref = "resteasy" }
resteasy-guice = { module = "org.jboss.resteasy:resteasy-guice" }
resteasy-jackson2-provider = { module = "org.jboss.resteasy:resteasy-jackson2-provider" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
solr-solrj = { module = "org.apache.solr:solr-solrj", version.ref = "solrj" }
typesafeconfig-guice = { module = "com.github.racc:typesafeconfig-guice", version.ref = "typesafeconfig" }
velocity-engine-core = { module = "org.apache.velocity:velocity-engine-core", version.ref = "velocity" }
zookeeper = { module = "org.apache.zookeeper:zookeeper", version.ref = "zookeeper" }
zookeeper-jute = { module = "org.apache.zookeeper:zookeeper-jute" }