[libraries]
assertj-core = { module = "org.assertj:assertj-core", version = "3.22.0" }
commons-io = { module = "commons-io:commons-io" }
guava = { module = "com.google.guava:guava" }
guice = { module = "com.google.inject:guice", version = "5.1.0" }
guice-servlet = { module = "com.google.inject.extensions:guice-servlet" }
httpcomponents-fluent-hc = { module = "org.apache.httpcomponents:fluent-hc", version = "4.5.13" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version = "2.13.5" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-datatype-json-org = { module = "com.fasterxml.jackson.datatype:jackson-datatype-json-org" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
jakarta-activation = { module = "com.sun.activation:jakarta.activation", version = "1.2.2" }
jakarta-inject-api = { module = "jakarta.inject:jakarta.inject-api", version = "1.0.5" }
jakarta-mail-impl = { module = "com.sun.mail:jakarta.mail", version = "1.6.7" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version = "4.0.4" }
jsr305 = { module = "com.google.code.findbugs:jsr305" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version = "5.8.2" }
opensaml = { module = "org.opensaml:opensaml", version = "2.6.4" }
org-json = { module = "org.json:json" }
org-reflections = { module = "org.reflections:reflections", version = "0.9.11" }
poi = { module = "org.apache.poi:poi", version = "5.2.2" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml" }
resteasy-core = { module = "org.jboss.resteasy:resteasy-core", version = "4.7.6.Final" }
resteasy-guice = { module = "org.jboss.resteasy:resteasy-guice" }
resteasy-jackson2-provider = { module = "org.jboss.resteasy:resteasy-jackson2-provider" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "1.7.36"}
slf4j-simple = { module = "org.slf4j:slf4j-simple" }
solr-solrj = { module = "org.apache.solr:solr-solrj", version = "7.7.3" }
typesafeconfig-guice = { module = "com.github.racc:typesafeconfig-guice", version = "0.1.0" }
velocity-engine-core = { module = "org.apache.velocity:velocity-engine-core", version = "2.3" }
zookeeper = { module = "org.apache.zookeeper:zookeeper", version = "3.8.0" }
zookeeper-jute = { module = "org.apache.zookeeper:zookeeper-jute" }